### ISSUE TITLE
Bug: Neovim cursor position outside buffer

### ISSUE THREAD

**Issue by vereym** [CFiggers/janet-lsp#37]
Hey, I'm having a problem using neovim with [fzf-lua](https://github.com/ibhagwan/fzf-lua) (through [lazyvim](https://www.lazyvim.org/).

I initially reported the bug in ibhagwan/fzf-lua#1687 but was told that it's more likely an upstream bug.

When trying to use hover on an identifier that's indented like `wibble` in the following example I also noticed that on the first character the lsp reports no information for the symbol but when going to the second it works. So maybe the document position is somehow off? 🤔

```janet
(defn wibble "some docs" [] :wibble)
(defn wobble [] :wobble)

(defn test [test]
  (wibble) (wobble))

(test "test")
```

**Comment by CFiggers** [comment]
Hey there—yeah that looks like a bug with Janet LSP. I'll look into it. Thanks for the report!

**Comment by ibhagwan** [comment]
Thanks for confirming @CFiggers!

**Comment by CFiggers** [comment]
Good morning @vereym . I just merged a bugfix that should address this issue. Could you please download the current master and see if that resolves it. Thanks!

**Comment by vereym** [comment]
Hey @CFiggers thanks for the quick update.
The offset bug seems fixed, but unfortunately the original bug with go to definition still persists.
If I have some time tomorrow, I'll try to look into it again as well.

On that note. I saw that there is some code to enable debug mode for a running lsp (which would be very useful to me for debugging a single instance of the lsp without having to change my config) but I couldn't figure out how to send messages to a running server.
Is not implemented yet, or did I just miss it? 🙂

**Comment by CFiggers** [comment]
> Hey @CFiggers thanks for the quick update.
> The offset bug seems fixed, but unfortunately the original bug with go to definition still persists.
> If I have some time tomorrow, I'll try to look into it again as well.

I'm happy to continue helping as I'm able. Let me know what you discover.
 
> On that note. I saw that there is some code to enable debug mode for a running lsp (which would be very useful to me for debugging a single instance of the lsp without having to change my config) but I couldn't figure out how to send messages to a running server.
> Is not implemented yet, or did I just miss it? 🙂 

You can start the server up in debug mode by passing `--debug` at the command line—however you have set up to do that. To enable debug mode while the server is running, you need to send a JSON RPC request to the server with the "enableDebug" remote method call and no parameters. There might be easier ways to do this in Neovim than I've discovered yet, but as a last-ditch option you can at least enter the following as a command and it should work:

`:lua vim.lsp.buf_request(0, "enableDebug", {}, function(err, result, ctx) end)`

Or you can bind the `vim.lsp.buf_request(0, "enableDebug", {}, function(err, result, ctx) end)` part to a keybind of your choosing.

The `enableDebug` method will instruct the running Janet LSP process to connect to a Janet LSP console, if there's one currently listening on localhost (you can start one from a different terminal window with `$ janet-lsp --console`) and, even if there isn't a console available, to start printing debug messages to `janetlsp.log` in the root directory that you launched Neovim from.

I'm developing Janet LSP in concert with [Janet++](https://GitHub.com/CFiggers/vscode-janet-plus-plus), a VS Code extension for Janet. That extension has facilities for interacting with the LSP that currently don't have a parallel for Neovim, including easily enabling and disabling debug mode and changing the detail level of debug messages.
